{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 24771,
          "sha512": "a57a7686f94dbb750aec6e0c9d9f8a6d63c99aa7cd692a0114fdf88e56b28d18f3da2647b8d4a9e5bac9e1127bab2d5cd4c20bc25bb2685a3067860bf6821609",
          "sha256": "a91b8d5e20ab169ee4661e8eefab0c5f63165bc6a1ea95670462b8c23403a1aa",
          "sha1": "71c4b48be80e6af293a03b7f869ba7a0d7cbd083",
          "md5": "e84dc1e08c3e7a9d8a423eb141136604"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 24771,
          "sha512": "a57a7686f94dbb750aec6e0c9d9f8a6d63c99aa7cd692a0114fdf88e56b28d18f3da2647b8d4a9e5bac9e1127bab2d5cd4c20bc25bb2685a3067860bf6821609",
          "sha256": "a91b8d5e20ab169ee4661e8eefab0c5f63165bc6a1ea95670462b8c23403a1aa",
          "sha1": "71c4b48be80e6af293a03b7f869ba7a0d7cbd083",
          "md5": "e84dc1e08c3e7a9d8a423eb141136604"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-1.0-sources.jar",
          "url": "url_launcher_android_debug-1.0-sources.jar",
          "size": 9032,
          "sha512": "527014b92da96b4ba92380975c02e461b0262c242a5288748f493f877a3a75f7b8a100f565e685cab63cbd6130d146eaa1154e6c9086029636d154f206cd337f",
          "sha256": "1996757e91b65e9561cd21c192f1f8f7b45b002986dbf98d2f8fe25ea7312acf",
          "sha1": "bdcac4c6b9603b74bef8b37940bc6823eb610679",
          "md5": "a165c0818ec736e2c2b3a24f1f69676d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-1.0-javadoc.jar",
          "url": "url_launcher_android_debug-1.0-javadoc.jar",
          "size": 331964,
          "sha512": "170cb204c63ad614b69542cc32d0a7a9f3695a168d7876490ea9f53af38077a1438ffee966b5a0cb3e6ec9a758377872249305b23cabc703301f8d03c6c31e29",
          "sha256": "62a389f033d3ac47246048c045bd826b7e69e5806295c1d93ac7781217f345cb",
          "sha1": "deebecf16ccafec9478d4149c9af89c0cdc4854e",
          "md5": "fa58b104808354af40f7ee7544252433"
        }
      ]
    }
  ]
}
