{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23567,
          "sha512": "4367f3a4f579309957b97050c27e02b2cc9f93694e4122eae0579b6ca368988f6385fc49b83931a76b380135c4d5ffcc224b41ef6377727e83f398a20cb42339",
          "sha256": "41553a17d761d30da2eb2bde000df7e49ec2d0d407eede603271a9c223760b85",
          "sha1": "61c038262ec86b77b597476fafe9d699fb225f19",
          "md5": "0fa0f6807a809e69398e94ca2f282c52"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23567,
          "sha512": "4367f3a4f579309957b97050c27e02b2cc9f93694e4122eae0579b6ca368988f6385fc49b83931a76b380135c4d5ffcc224b41ef6377727e83f398a20cb42339",
          "sha256": "41553a17d761d30da2eb2bde000df7e49ec2d0d407eede603271a9c223760b85",
          "sha1": "61c038262ec86b77b597476fafe9d699fb225f19",
          "md5": "0fa0f6807a809e69398e94ca2f282c52"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-sources.jar",
          "url": "url_launcher_android_profile-1.0-sources.jar",
          "size": 9020,
          "sha512": "860ece7df512342ab9fe4d543deab83a88d344d8932a60109db57e8ed5cef4568956699644bc0e84a8773be686fa25f92866db6ff0a986425411b634a62b8be6",
          "sha256": "4a7360119075a89f5decc99769fbdbef6c751992d08c0b3a7b11be5538d59f72",
          "sha1": "cd49b9f2083c1dbf9d3a2d0ebbfbdaf402642ac4",
          "md5": "bd385636b0de71ab06756149b825cf0f"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-javadoc.jar",
          "url": "url_launcher_android_profile-1.0-javadoc.jar",
          "size": 331962,
          "sha512": "d42b071817b33b1c8adb8f3d573529a97413eac0e4c2b6ffd06e8eae695110dbcc1d26c22a10744d6c7c4ae22ec1c3a971de25def2eea0558dada785667c8c95",
          "sha256": "b49c82d8d030c85be689b123cc58337df16cd71bb33304e604ba7b0f56e91bc7",
          "sha1": "1f06aed0fffb014eb93cafef71a2e43d97e1e133",
          "md5": "0f70dda821b91baf3945cdde99935cb5"
        }
      ]
    }
  ]
}
