{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 99716,
          "sha512": "769e5ba3468f40fa75bdef6cf981efa94b4917505d5dcb7fc4fc91ccb818b09f0743fd9a20500ee59831f5bd0583417cb5dbf0ca0acf15117c2d905fadad2b58",
          "sha256": "a9acbc3d66482f3d28cd840f95255b10c50c795f9f0294e4d60c22ab05c35132",
          "sha1": "d5b8ff2c184048fa9adc7d2697dfc0c07dd9de44",
          "md5": "80b8417c88a94ae838c456cee455e37c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 99716,
          "sha512": "769e5ba3468f40fa75bdef6cf981efa94b4917505d5dcb7fc4fc91ccb818b09f0743fd9a20500ee59831f5bd0583417cb5dbf0ca0acf15117c2d905fadad2b58",
          "sha256": "a9acbc3d66482f3d28cd840f95255b10c50c795f9f0294e4d60c22ab05c35132",
          "sha1": "d5b8ff2c184048fa9adc7d2697dfc0c07dd9de44",
          "md5": "80b8417c88a94ae838c456cee455e37c"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0-sources.jar",
          "url": "shared_preferences_android_debug-1.0-sources.jar",
          "size": 10789,
          "sha512": "e3e012a027ca44ec7e65dc50a5773cc60491b0a117425f86c83d3e163d273ac58cd4b876822de07b15e4b0ecadfbd70edff85f7e38de60d9c18724e4ea09748a",
          "sha256": "36a273fcd563eca270a295b75fd3fd1858b2889399615cf34f043d15354df092",
          "sha1": "d5de284966d3e33de67c2c091cd605dcfe2e8958",
          "md5": "52b878f383e8fad7ef3b2fc6e775afcc"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0-javadoc.jar",
          "url": "shared_preferences_android_debug-1.0-javadoc.jar",
          "size": 330540,
          "sha512": "85367f60e57e51099990ef7ef5a35c11133afde815fa1fe0ac7a57f8b47c0bce52f40e4181562b2ed9f63886e99270b004ad3a02e3ea0d487e12702b8b340618",
          "sha256": "a05f05968356d2e3b720dd041c586392d4ea0a58bdd88b1d40f2e5120e988764",
          "sha1": "e97138d16047945cb0e88525e3f333902e481533",
          "md5": "b874516cba2579ca2e968af4126b1216"
        }
      ]
    }
  ]
}
