{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vr.helloworldmodule",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 8885187,
          "sha512": "3dddffbfe15e59f52bd3ede82e3512631a40f3d77e916e3db7e6cc045e8607cd64c284c36f68862291ceffed4e20c6decda0b3dd1eab6e88a27933f35cd3e3e3",
          "sha256": "f5727631bbfd7e6b4a4ec5407627d8d6dd5d595122060ae8f413fd3c7d981718",
          "sha1": "f8df8a5ecaf53d95931f0556393b4b91cfc418da",
          "md5": "ecc6383656f91238a9274d948e543a92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 8885187,
          "sha512": "3dddffbfe15e59f52bd3ede82e3512631a40f3d77e916e3db7e6cc045e8607cd64c284c36f68862291ceffed4e20c6decda0b3dd1eab6e88a27933f35cd3e3e3",
          "sha256": "f5727631bbfd7e6b4a4ec5407627d8d6dd5d595122060ae8f413fd3c7d981718",
          "sha1": "f8df8a5ecaf53d95931f0556393b4b91cfc418da",
          "md5": "ecc6383656f91238a9274d948e543a92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-sources.jar",
          "url": "flutter_release-1.0-sources.jar",
          "size": 1856,
          "sha512": "945b0362e2df7a27062ca353133489faec36f353d952091e988486605dc32e17b1d9de2936c21676adbe1362507250e3b1783d77499fd042ac19f5f5eeee91d4",
          "sha256": "4aacb616ba16657fadb892fa1c0bef4507f64dfa973541bea1039c1bcc03b803",
          "sha1": "8bd8f85f2b08d64ea625060fd52678325805a72c",
          "md5": "008701e1833540501e617ff91489fb6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-javadoc.jar",
          "url": "flutter_release-1.0-javadoc.jar",
          "size": 269303,
          "sha512": "f00d7bd64cdc43e61236226e8d95deb4770fcedbf97991e342a6df5e9673e0ea7e683571ed9a82d272a21204f24e28c018e5f481c07f547cc137e3aaeb99a26a",
          "sha256": "25a340dd608e612b575e6b3b4b19b73cfe96c83c506839dedbc571400016471b",
          "sha1": "f4029efc9f8b59f1742911de0a6f62f2c1bd378b",
          "md5": "5d3737e39479a9e1157f647e90297823"
        }
      ]
    }
  ]
}
