{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vr.helloworldmodule",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 12051791,
          "sha512": "2c9164ac95d14c2582fd5d261bc73ef4cc479423249c84c15ae0f774979ab9936ab110033b00b7f4db82aeb8914cc69c2f819dc6f72c50178f62cf218375ff11",
          "sha256": "8724ab2733394a9d229a4ab482af42c3b9a8a7af106b240bf036fa88a879e15b",
          "sha1": "30155cb70a56c2b84f9f7dc88fc57d49f74751f0",
          "md5": "19109cba5c6843874284489046de596b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 12051791,
          "sha512": "2c9164ac95d14c2582fd5d261bc73ef4cc479423249c84c15ae0f774979ab9936ab110033b00b7f4db82aeb8914cc69c2f819dc6f72c50178f62cf218375ff11",
          "sha256": "8724ab2733394a9d229a4ab482af42c3b9a8a7af106b240bf036fa88a879e15b",
          "sha1": "30155cb70a56c2b84f9f7dc88fc57d49f74751f0",
          "md5": "19109cba5c6843874284489046de596b"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1870,
          "sha512": "bde6c6208dd40308abfbbae2a9995975f24a864f84dc8a92ca0cdf08e33afd212012f5756b5e5a50a6ff3f8db0432a8c851a14c245e82bd5e9aa364791613327",
          "sha256": "9a84a1c13a23fc65db2322825ae67a18c5e65d9e2fb36fa33e6a522c1643f594",
          "sha1": "3ad7cb45f1f051e411f3ec20fa3a78813717164b",
          "md5": "b80d934855dd3a8c586e6cdaeb668126"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 269304,
          "sha512": "7f35e2219f883601704fc5e45360305affee628d630d8992c6bac959e4b159fd0cea2bd5d2838809ba4a2b474bfd36e586bba1bf87a31ee72bdb8b766dfea489",
          "sha256": "2124bc83982f27d03a9edaf4995c7a632bd346daabdc5a283c5c80c592375800",
          "sha1": "17a4955938c530e8bc32190ce97e2b54032272ed",
          "md5": "1499f370632e2c952a500803d0cf0b6c"
        }
      ]
    }
  ]
}
