{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vr.helloworldmodule",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23763810,
          "sha512": "f3ca20a4684917fd8cf98e9f00be88f9ac2092d2df6c7fca6ebbe07eac5f7c2b7cab6dbf4e105e59fe625b84ee13ffce6b47e4f1e6645f07d03e0863909ce306",
          "sha256": "3f9365202cf0c0fb4961393772016df326ed6f242bcf4bf2ab3377c6e96f5de5",
          "sha1": "30e44aaec84f48394f50953e733012f30e7b6ed6",
          "md5": "3a011cc812c7613247cf7421bc9c10fd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23763810,
          "sha512": "f3ca20a4684917fd8cf98e9f00be88f9ac2092d2df6c7fca6ebbe07eac5f7c2b7cab6dbf4e105e59fe625b84ee13ffce6b47e4f1e6645f07d03e0863909ce306",
          "sha256": "3f9365202cf0c0fb4961393772016df326ed6f242bcf4bf2ab3377c6e96f5de5",
          "sha1": "30e44aaec84f48394f50953e733012f30e7b6ed6",
          "md5": "3a011cc812c7613247cf7421bc9c10fd"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1868,
          "sha512": "40ce3e2c3edbcfddd4ff3e728e48ec6c74777d84029f5e7ced3d9b98671c4f16a66c3d34b8f6cda228ebf26e3c619e81451180ae980b2a335a369c0c3b0eda61",
          "sha256": "53eead1d5b88170e47c9c7ad553accac461c78adcee766ed07cfc07e630c6032",
          "sha1": "a51d0871a0da7ce4c9bf0016e3c1b1c42dfecb1b",
          "md5": "07798fd59fb734c151792b32e4d67848"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 269304,
          "sha512": "7f35e2219f883601704fc5e45360305affee628d630d8992c6bac959e4b159fd0cea2bd5d2838809ba4a2b474bfd36e586bba1bf87a31ee72bdb8b766dfea489",
          "sha256": "2124bc83982f27d03a9edaf4995c7a632bd346daabdc5a283c5c80c592375800",
          "sha1": "17a4955938c530e8bc32190ce97e2b54032272ed",
          "md5": "1499f370632e2c952a500803d0cf0b6c"
        }
      ]
    }
  ]
}
