{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 94969,
          "sha512": "384dfc76c509f7b4f2c284e0dd050bcbe20714d0698f633cd45399e3c8225feefdf028297ac971eb52ea5a06f443c1ccd94cd8bc572a272d6a8f2d842a454a71",
          "sha256": "0e7d4337813ee642b9b9d26a7b64418c1f0aed2f168b9f4ed9169c9d969a57b9",
          "sha1": "6eb5a7f76fc9e206ad312cfb29e71e74ef90593f",
          "md5": "8b7c1afc2aee05d6c66eaaf6357d8653"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 94969,
          "sha512": "384dfc76c509f7b4f2c284e0dd050bcbe20714d0698f633cd45399e3c8225feefdf028297ac971eb52ea5a06f443c1ccd94cd8bc572a272d6a8f2d842a454a71",
          "sha256": "0e7d4337813ee642b9b9d26a7b64418c1f0aed2f168b9f4ed9169c9d969a57b9",
          "sha1": "6eb5a7f76fc9e206ad312cfb29e71e74ef90593f",
          "md5": "8b7c1afc2aee05d6c66eaaf6357d8653"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0-sources.jar",
          "url": "shared_preferences_android_profile-1.0-sources.jar",
          "size": 10777,
          "sha512": "cdf665f0ed166017f16d791218db81110b33349e375ade77da60ca60aedfdbe205274d97518d332fe68582c5309858428cb48bc77b9eec25e2d9aee5af3ae14a",
          "sha256": "0e693e6cd37fe596552fff21d29892b4fc3ebcce0de25104351165cff44b4c7b",
          "sha1": "6a482605dc0bd350d2c82c73b94270292cc66fd2",
          "md5": "74557883a90f36b9bb0388905e69e624"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0-javadoc.jar",
          "url": "shared_preferences_android_profile-1.0-javadoc.jar",
          "size": 330546,
          "sha512": "c5fb90dbe368ec1129674e67c7fe9e59a8f61495cacb13771ac43e89ddd97b5292e014f8be89e80c7bb888779804612ce41adb56d08ef11371c612f51206648b",
          "sha256": "3db16eca1c9221242243347cb4f0f6811adf3480de8b0a67ac168941e90f7e9d",
          "sha1": "d14109d897744931b0b1011186ea4638684a8e3a",
          "md5": "45219dc868b9f62a37d938faea40404d"
        }
      ]
    }
  ]
}
