{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vr.helloworldmodule",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 12109724,
          "sha512": "155351c68bff3b2e1a4308ddc98e441e962120b822f3e0a1d06c30f22c5bd2cc6549de4dcb482b0b82ea13f2b15a6f8f93e5d5a38bf6db70369ba252effcfa31",
          "sha256": "2ea9352414511ca977b3f8ac5c6ece2865cbd919ca6424d632c32ce16accceec",
          "sha1": "7a4e6b084b1050ae21cc44411a3250b83b0c7759",
          "md5": "9c4c842da37b9c1dca0d38ca83c6b847"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 12109724,
          "sha512": "155351c68bff3b2e1a4308ddc98e441e962120b822f3e0a1d06c30f22c5bd2cc6549de4dcb482b0b82ea13f2b15a6f8f93e5d5a38bf6db70369ba252effcfa31",
          "sha256": "2ea9352414511ca977b3f8ac5c6ece2865cbd919ca6424d632c32ce16accceec",
          "sha1": "7a4e6b084b1050ae21cc44411a3250b83b0c7759",
          "md5": "9c4c842da37b9c1dca0d38ca83c6b847"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1870,
          "sha512": "bde6c6208dd40308abfbbae2a9995975f24a864f84dc8a92ca0cdf08e33afd212012f5756b5e5a50a6ff3f8db0432a8c851a14c245e82bd5e9aa364791613327",
          "sha256": "9a84a1c13a23fc65db2322825ae67a18c5e65d9e2fb36fa33e6a522c1643f594",
          "sha1": "3ad7cb45f1f051e411f3ec20fa3a78813717164b",
          "md5": "b80d934855dd3a8c586e6cdaeb668126"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 269304,
          "sha512": "7f35e2219f883601704fc5e45360305affee628d630d8992c6bac959e4b159fd0cea2bd5d2838809ba4a2b474bfd36e586bba1bf87a31ee72bdb8b766dfea489",
          "sha256": "2124bc83982f27d03a9edaf4995c7a632bd346daabdc5a283c5c80c592375800",
          "sha1": "17a4955938c530e8bc32190ce97e2b54032272ed",
          "md5": "1499f370632e2c952a500803d0cf0b6c"
        }
      ]
    }
  ]
}
