{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 48244,
          "sha512": "15c16eff6d13af2f3258d42780ab7bf30ece709ef274ccad0ddf337906d591a47d1280413ab3735a37a872cf2a2754c86186ce6f4dfa8bd246686de659989ede",
          "sha256": "b6a9cb83f4e5b0d9dfa0996e4c1b5264fe0a8b0a22fa3356e288f3f54c014463",
          "sha1": "aa32e5638fd02574617e248dec8e019ed6353957",
          "md5": "f5d4b0686a6e7dba406f8e1af019765d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 48244,
          "sha512": "15c16eff6d13af2f3258d42780ab7bf30ece709ef274ccad0ddf337906d591a47d1280413ab3735a37a872cf2a2754c86186ce6f4dfa8bd246686de659989ede",
          "sha256": "b6a9cb83f4e5b0d9dfa0996e4c1b5264fe0a8b0a22fa3356e288f3f54c014463",
          "sha1": "aa32e5638fd02574617e248dec8e019ed6353957",
          "md5": "f5d4b0686a6e7dba406f8e1af019765d"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_debug-1.0-sources.jar",
          "url": "sqflite_debug-1.0-sources.jar",
          "size": 24262,
          "sha512": "96823b7b15b1897f943a297a317f3e94730a4c86a61408430ae6deeb184e5545d26d8bbf297813002aee4564cdec3846889d3a486c6e266cca947dea2f5d509e",
          "sha256": "2d5079be2a64b68af85df6f91c6326423c23014d5c56702f28b21d8e3dd85932",
          "sha1": "fb9217779cc3059519b27e3f42b97c2361d061fc",
          "md5": "4675f84c07c06bc18681bb9bdc0ed457"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_debug-1.0-javadoc.jar",
          "url": "sqflite_debug-1.0-javadoc.jar",
          "size": 343931,
          "sha512": "20df7fef4e1e348b7d1b1434cac196f253efdd46efc5b9d84b4f9a2e8f0f3959529ee31f24f150b7144accba65d3aab90440eb3cdb2f233908f90b056edca268",
          "sha256": "e11a449e73389f69b8f29f778a0106a40875da1ff2512ba86c13f0af72505331",
          "sha1": "62c1391ac287fc6ed365caa6e61b1b8a8742392b",
          "md5": "760d309c5fa0541242f12b246958893b"
        }
      ]
    }
  ]
}
