{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12862,
          "sha512": "842564bc431a016a6edee1bbbf149b0278b61619c033614e70830ac0507ee2d7751134129a423662d61f68a1990d6ea4340abb6ced473100d3793311d3d35987",
          "sha256": "802895778fbde064c63db164ed1f7519532f708e460f1302ae7634fec3f8f616",
          "sha1": "ac3183d5b202570a5f5736f31927307a7b979751",
          "md5": "55a1b4abaa1d5e58030df48e0631fafa"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12862,
          "sha512": "842564bc431a016a6edee1bbbf149b0278b61619c033614e70830ac0507ee2d7751134129a423662d61f68a1990d6ea4340abb6ced473100d3793311d3d35987",
          "sha256": "802895778fbde064c63db164ed1f7519532f708e460f1302ae7634fec3f8f616",
          "sha1": "ac3183d5b202570a5f5736f31927307a7b979751",
          "md5": "55a1b4abaa1d5e58030df48e0631fafa"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-sources.jar",
          "url": "path_provider_android_profile-1.0-sources.jar",
          "size": 5062,
          "sha512": "a29b3bed0383f4dd981a1efad0f0813e37b8ef7e8558eb764440f63917c39ca2c69752a4465a4053890e39c992c8fead3600ed2a93164bce1ee4b31ee710904c",
          "sha256": "89a4ff88172db6dab1a05fff549cbde56e0f54b6e9ea4623e90c0c1649d0f105",
          "sha1": "cf5cfed64849d444a0f2f70dd3557005dd331e8d",
          "md5": "bd06d61ab71bcb385c1386c324a6cbea"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-javadoc.jar",
          "url": "path_provider_android_profile-1.0-javadoc.jar",
          "size": 298163,
          "sha512": "43cc298e38bc2af3be553bc5655f03056e32293637c345d080dc582751c98830d0c13b5c0eaf28104e9bc47a151cf118c2c14a3cd83489fb8f69a11c38e74ca3",
          "sha256": "14b2032e916c6e7422bb4475045a85d820af5cc0b67348593eade9ec71f592eb",
          "sha1": "b286d946952d176dc0c25eca138afe85297af76e",
          "md5": "aa127abdfe1b377a9b7f9a70e9b40ef6"
        }
      ]
    }
  ]
}
