{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 94976,
          "sha512": "b33a8324805e9b007235f5de11b5621d115e65ee69f496657bfcaa45b8b6257200ff9cee24ce79d329d434ace5b225c85318bfcc44a74a361895507e1ed15695",
          "sha256": "635856e2a0820f2e93c5f925513168022e285191ed90af3b14cdb8cdeb7a2b46",
          "sha1": "b1c3347fa149d6e6603123b8d485a9f318b82d11",
          "md5": "b0d72571e14fcdc4f4b9b74e3c5324f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 94976,
          "sha512": "b33a8324805e9b007235f5de11b5621d115e65ee69f496657bfcaa45b8b6257200ff9cee24ce79d329d434ace5b225c85318bfcc44a74a361895507e1ed15695",
          "sha256": "635856e2a0820f2e93c5f925513168022e285191ed90af3b14cdb8cdeb7a2b46",
          "sha1": "b1c3347fa149d6e6603123b8d485a9f318b82d11",
          "md5": "b0d72571e14fcdc4f4b9b74e3c5324f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-sources.jar",
          "url": "shared_preferences_android_release-1.0-sources.jar",
          "size": 10775,
          "sha512": "ea7edd6d9d46f3dac8cdcffee124bba372a80989d945829aabb3fd236e97fb1062178936d8c0a4c1d4f2b7d844bd7da8e201553d57bb28eac29228da9359c98b",
          "sha256": "8960e9670f106195142b318f1ed96933b01f0f2b6ac40d929a62f510f445f2e8",
          "sha1": "ebce0968fc26c4a9c57c515b7094f6302310fe5c",
          "md5": "4d9e2874f6fd88e3330b77548e0981c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-javadoc.jar",
          "url": "shared_preferences_android_release-1.0-javadoc.jar",
          "size": 330546,
          "sha512": "c5fb90dbe368ec1129674e67c7fe9e59a8f61495cacb13771ac43e89ddd97b5292e014f8be89e80c7bb888779804612ce41adb56d08ef11371c612f51206648b",
          "sha256": "3db16eca1c9221242243347cb4f0f6811adf3480de8b0a67ac168941e90f7e9d",
          "sha1": "d14109d897744931b0b1011186ea4638684a8e3a",
          "md5": "45219dc868b9f62a37d938faea40404d"
        }
      ]
    }
  ]
}
